# Generated by Django 4.2.2 on 2023-07-02 08:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
