# Generated by Django 4.2.2 on 2023-07-02 08:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0003_auto_20230702_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
